# -*- coding: utf-8 -*-
# copyright 2025 Snow Leopard, Inc


# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///

"""
Convert the Kaggle Metacritic games CSV into a PostgreSQL script.

The output SQL file creates a single ``metacritic`` table and inserts every row from the CSV.
Load it into a PostgreSQL database that Snow Leopard Cloud can reach:

    psql "$DATABASE_URL" -f metacritic.sql

Usage:
    uv run scripts/preparedata.py result.csv metacritic.sql
"""

import argparse
import csv
import os
import sys

from datetime import datetime


program_name = 'preparedata'
program_description = 'convert metacritic csv file to a PostgreSQL script'

ROWS_PER_INSERT = 500

CREATE_TABLE_SQL = """\
-- Metacritic games dataset for the Snow Leopard CrewAI game club example.
-- Generated by scripts/preparedata.py from the Kaggle dataset:
--   https://www.kaggle.com/datasets/destring/metacritic-reviewed-games-since-2000
-- Load with:  psql "$DATABASE_URL" -f metacritic.sql

DROP TABLE IF EXISTS metacritic;

CREATE TABLE metacritic (
    metascore_percent INTEGER,
    name TEXT NOT NULL,
    console TEXT,
    userscore_10_points REAL,
    release_date DATE
);
COMMENT ON TABLE metacritic IS 'Metacritic critic and user scores for video games released since 2000, one row per game and platform';
COMMENT ON COLUMN metacritic.metascore_percent IS 'aggregate critic score from 0 to 100';
COMMENT ON COLUMN metacritic.console IS 'platform the game was released on, e.g. PC, PlayStation 4, Switch';
COMMENT ON COLUMN metacritic.userscore_10_points IS 'aggregate user score from 0 to 10; NULL when Metacritic had not calculated one yet';
"""


def str_to_float_with_null_tbd(s):
    """
    dataset-specific converter from string to float.  the dataset uses "tbd" when a userscore
    hasn't been calculated yet.
    """
    s = s.strip()
    return None if s.lower() in ('tbd', '') else float(s)


def short_us_date_str_to_date(s):
    """
    parse abbreviated US-ordered date string (e.g. 'Oct 10, 2017') into a datetime.date
    """
    return datetime.strptime(s.strip(), '%b %d, %Y').date()


def get_metacritic_table_def():
    """
    return (table_name, column_defs) tuple, where:
      table_name, str: name of the table to create
      columns, dict[str, column_def]: the set of columns to create, order is preserved, where
        keys are the name of the column header from the .csv, and values are:
        column_def, tuple[str, Callable]: the column name in the table and a converter function
          from the string value in the .csv to the desired python value.
    """
    columns = {
        'metascore': ('metascore_percent', int),
        'name': ('name', str),
        'console': ('console', str),
        'userscore': ('userscore_10_points', str_to_float_with_null_tbd),
        'date': ('release_date', short_us_date_str_to_date),
    }

    return 'metacritic', columns


def sql_literal(value):
    """render a python value as a SQL literal"""
    if value is None:
        return 'NULL'
    if isinstance(value, (int, float)):
        return repr(value)
    if hasattr(value, 'isoformat'):
        return f"'{value.isoformat()}'"
    return "'" + str(value).replace("'", "''") + "'"


def csv_to_sql(sql_file, csv_reader, table_name, columns):
    """
    write CREATE TABLE and INSERT statements for the contents of a csv.DictReader to an open file
    """
    missing = [fieldname for fieldname in columns if fieldname not in csv_reader.fieldnames]
    if missing:
        raise ValueError(f"exact match(es) for column definition not found for: {', '.join(missing)}")

    column_names = [column_name for column_name, _ in columns.values()]
    sql_file.write(CREATE_TABLE_SQL)
    sql_file.write('\n')

    count = 0
    chunk = []

    def flush():
        if chunk:
            sql_file.write(f"INSERT INTO {table_name} ({', '.join(column_names)}) VALUES\n")
            sql_file.write(',\n'.join('    (' + ', '.join(sql_literal(v) for v in row) + ')' for row in chunk))
            sql_file.write(';\n\n')
            chunk.clear()

    for line_number, row in enumerate(csv_reader, start=2):
        try:
            values = [converter(row[fieldname]) for fieldname, (_, converter) in columns.items()]
        except (ValueError, TypeError) as e:
            raise ValueError(f'line {line_number}: {e}') from e
        chunk.append(values)
        count += 1
        if len(chunk) >= ROWS_PER_INSERT:
            flush()
    flush()
    return count


def csv_to_sql_from_path(sql_path, csv_path, table_name, columns):
    """
    convert the contents of a .csv file at a given path to a PostgreSQL script at sql_path
    """
    # NOTE: csv.reader() requires the newline='' kwarg for open()
    with open(csv_path, 'r', newline='', encoding='utf-8') as csv_file, \
            open(sql_path, 'w', encoding='utf-8') as sql_file:
        csv_reader = csv.DictReader(csv_file)
        return csv_to_sql(sql_file, csv_reader, table_name, columns)


def parse_args(argv):
    parser = argparse.ArgumentParser(prog=program_name, description=program_description)

    parser.add_argument('--clean', '-c', action='store_true', help='when present, replace an existing output file')
    parser.add_argument('csvfile', help='the metacritic CSV file')
    parser.add_argument('sqlfile', help='the PostgreSQL script to write')

    return parser.parse_args(argv)


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]
    args = parse_args(argv)

    # handle --clean option
    if os.path.exists(args.sqlfile):
        if not args.clean:
            print('refusing to replace output file without `--clean`:', repr(args.sqlfile))
            return 1
        os.unlink(args.sqlfile)

    table_name, columns = get_metacritic_table_def()

    count = csv_to_sql_from_path(args.sqlfile, args.csvfile, table_name, columns)
    print(f'wrote {count} rows to {args.sqlfile}')
    print('next: load it into PostgreSQL, e.g.  psql "$DATABASE_URL" -f', args.sqlfile)
    return 0


if __name__ == '__main__':
    sys.exit(main())
