#!/usr/bin/env python3
"""
Convert the Kaggle "Personal Finance" CSV into a PostgreSQL script.

The output, ``finance_coach.sql``, creates a small normalized schema (users, accounts, categories,
merchants, transactions) plus three reporting views, and inserts every transaction from the CSV.
Load it into a PostgreSQL database that Snow Leopard Cloud can reach:

    psql "$DATABASE_URL" -f data/finance_coach.sql

Usage:
    python data/transform_personal_finance.py                # uses the CSV bundled in data/personal_finance/
    python data/transform_personal_finance.py my.csv -o out.sql

CSV columns expected (see data/personal_finance/column_description.md):
    Date, Description, Amount, Transaction Type, Category, Account Name, Month

The script uses only the Python standard library.
"""

import argparse
import csv
import sys
from collections import Counter, defaultdict
from datetime import datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_CSV = HERE / 'personal_finance' / 'personal_transactions_dashboard_ready(2).csv'
DEFAULT_OUT = HERE / 'finance_coach.sql'
ROWS_PER_INSERT = 100

SCHEMA_SQL = """\
-- Personal finance dataset for the Snow Leopard Financial Coach example.
-- Generated by data/transform_personal_finance.py from the Kaggle "Personal Finance" dataset:
--   https://www.kaggle.com/datasets/entrepreneurlife/personal-finance/data
-- Load with:  psql "$DATABASE_URL" -f data/finance_coach.sql

DROP VIEW IF EXISTS vw_top_merchants;
DROP VIEW IF EXISTS vw_monthly_spending;
DROP VIEW IF EXISTS vw_spending_by_category;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS merchants;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    email TEXT
);

CREATE TABLE accounts (
    account_id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    account_name TEXT NOT NULL UNIQUE,
    account_type TEXT NOT NULL
);
COMMENT ON COLUMN accounts.account_type IS 'checking or credit';

CREATE TABLE categories (
    category_id INTEGER PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE,
    category_type TEXT NOT NULL
);
COMMENT ON COLUMN categories.category_type IS 'expense, income, or transfer (credit card payments move money between accounts)';

CREATE TABLE merchants (
    merchant_id INTEGER PRIMARY KEY,
    merchant_name TEXT NOT NULL UNIQUE,
    category_id INTEGER REFERENCES categories(category_id)
);
COMMENT ON COLUMN merchants.category_id IS 'the category most often used for this merchant';

CREATE TABLE transactions (
    transaction_id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    account_id INTEGER NOT NULL REFERENCES accounts(account_id),
    merchant_id INTEGER NOT NULL REFERENCES merchants(merchant_id),
    category_id INTEGER NOT NULL REFERENCES categories(category_id),
    transaction_date DATE NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    transaction_type TEXT NOT NULL,
    month TEXT NOT NULL,
    description TEXT
);
COMMENT ON COLUMN transactions.amount IS 'always positive; transaction_type says whether money left (debit) or arrived (credit)';
COMMENT ON COLUMN transactions.transaction_type IS 'debit = money spent or paid out, credit = money received';
COMMENT ON COLUMN transactions.month IS 'transaction month as YYYY-MM';

CREATE INDEX idx_trans_date ON transactions(transaction_date);
CREATE INDEX idx_trans_category ON transactions(category_id);
CREATE INDEX idx_trans_account ON transactions(account_id);
CREATE INDEX idx_trans_merchant ON transactions(merchant_id);
CREATE INDEX idx_trans_user ON transactions(user_id);
"""

VIEWS_SQL = """\
CREATE VIEW vw_spending_by_category AS
SELECT
    c.category_name,
    SUM(t.amount) AS total_spent,
    COUNT(*) AS transaction_count,
    AVG(t.amount) AS avg_transaction
FROM transactions t
JOIN categories c ON t.category_id = c.category_id
WHERE t.transaction_type = 'debit'
GROUP BY c.category_name
ORDER BY total_spent DESC;

CREATE VIEW vw_monthly_spending AS
SELECT
    t.month,
    SUM(CASE WHEN t.transaction_type = 'debit' THEN t.amount ELSE 0 END) AS total_expenses,
    SUM(CASE WHEN t.transaction_type = 'credit' THEN t.amount ELSE 0 END) AS total_income,
    COUNT(*) AS transaction_count
FROM transactions t
GROUP BY t.month
ORDER BY t.month DESC;

CREATE VIEW vw_top_merchants AS
SELECT
    m.merchant_name,
    c.category_name,
    SUM(t.amount) AS total_spent,
    COUNT(*) AS frequency
FROM transactions t
JOIN merchants m ON t.merchant_id = m.merchant_id
JOIN categories c ON t.category_id = c.category_id
WHERE t.transaction_type = 'debit'
GROUP BY m.merchant_name, c.category_name
ORDER BY total_spent DESC;
"""


def sql_literal(value):
    """Render a Python value as a SQL literal."""
    if value is None:
        return 'NULL'
    if isinstance(value, (int, Decimal)):
        return str(value)
    if isinstance(value, datetime):
        return f"'{value.date().isoformat()}'"
    return "'" + str(value).replace("'", "''") + "'"


def insert_statements(table, columns, rows):
    """Yield multi-row INSERT statements for ``rows`` (iterables of Python values)."""
    rows = list(rows)
    for start in range(0, len(rows), ROWS_PER_INSERT):
        chunk = rows[start:start + ROWS_PER_INSERT]
        values = ',\n'.join('    (' + ', '.join(sql_literal(v) for v in row) + ')' for row in chunk)
        yield f"INSERT INTO {table} ({', '.join(columns)}) VALUES\n{values};\n"


def parse_row(row, line_number):
    """Validate and convert one CSV row into typed values."""
    try:
        date = datetime.strptime(row['Date'].strip()[:10], '%Y-%m-%d')
        amount = Decimal(row['Amount'].strip()).quantize(Decimal('0.01'))
    except (KeyError, ValueError, InvalidOperation) as e:
        raise ValueError(f'line {line_number}: could not parse Date/Amount: {e}') from e
    transaction_type = row['Transaction Type'].strip().lower()
    if transaction_type not in ('debit', 'credit'):
        raise ValueError(f"line {line_number}: unexpected Transaction Type {row['Transaction Type']!r}")
    return {
        'date': date,
        'merchant': row['Description'].strip(),
        'amount': amount,
        'transaction_type': transaction_type,
        'category': row['Category'].strip(),
        'account': row['Account Name'].strip(),
        'month': row['Month'].strip() or date.strftime('%Y-%m'),
    }


def load_csv(csv_path):
    with open(csv_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        return [parse_row(row, n) for n, row in enumerate(reader, start=2)]


def build_sql(rows):
    """Return the full SQL script for a list of parsed rows."""
    # Lookup tables, numbered in order of first appearance so the output is deterministic.
    accounts = {}
    categories = {}
    merchants = {}
    category_types = defaultdict(set)
    merchant_categories = defaultdict(Counter)
    for r in rows:
        accounts.setdefault(r['account'], len(accounts) + 1)
        categories.setdefault(r['category'], len(categories) + 1)
        merchants.setdefault(r['merchant'], len(merchants) + 1)
        category_types[r['category']].add(r['transaction_type'])
        merchant_categories[r['merchant']][r['category']] += 1

    def category_type(name):
        kinds = category_types[name]
        if kinds == {'credit'}:
            return 'income'
        if kinds == {'debit', 'credit'}:
            return 'transfer'
        return 'expense'

    user_id = 1
    out = [SCHEMA_SQL, '']
    out.extend(insert_statements('users', ('user_id', 'name', 'email'), [(user_id, 'Default User', None)]))
    out.extend(insert_statements(
        'accounts', ('account_id', 'user_id', 'account_name', 'account_type'),
        [(aid, user_id, name, 'checking' if 'checking' in name.lower() else 'credit') for name, aid in accounts.items()],
    ))
    out.extend(insert_statements(
        'categories', ('category_id', 'category_name', 'category_type'),
        [(cid, name, category_type(name)) for name, cid in categories.items()],
    ))
    out.extend(insert_statements(
        'merchants', ('merchant_id', 'merchant_name', 'category_id'),
        [(mid, name, categories[merchant_categories[name].most_common(1)[0][0]]) for name, mid in merchants.items()],
    ))
    out.extend(insert_statements(
        'transactions',
        ('transaction_id', 'user_id', 'account_id', 'merchant_id', 'category_id',
         'transaction_date', 'amount', 'transaction_type', 'month', 'description'),
        [(i, user_id, accounts[r['account']], merchants[r['merchant']], categories[r['category']],
          r['date'], r['amount'], r['transaction_type'], r['month'], r['merchant'])
         for i, r in enumerate(rows, start=1)],
    ))
    out.append('')
    out.append(VIEWS_SQL)
    return '\n'.join(out), {
        'accounts': len(accounts), 'categories': len(categories),
        'merchants': len(merchants), 'transactions': len(rows),
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description='Convert the personal finance CSV to a PostgreSQL script')
    parser.add_argument('csv_file', nargs='?', default=DEFAULT_CSV, help=f'input CSV (default: {DEFAULT_CSV.name})')
    parser.add_argument('-o', '--output', default=DEFAULT_OUT, help=f'output SQL file (default: {DEFAULT_OUT.name})')
    args = parser.parse_args(argv)

    csv_path = Path(args.csv_file)
    if not csv_path.exists():
        print(f'error: {csv_path} not found. Download the dataset from '
              'https://www.kaggle.com/datasets/entrepreneurlife/personal-finance/data', file=sys.stderr)
        return 1

    rows = load_csv(csv_path)
    sql, counts = build_sql(rows)
    Path(args.output).write_text(sql, encoding='utf-8')

    print(f'Wrote {args.output}')
    for table, n in counts.items():
        print(f'  {table}: {n} rows')
    print('\nNext: load it into PostgreSQL, e.g.  psql "$DATABASE_URL" -f', args.output)
    return 0


if __name__ == '__main__':
    sys.exit(main())
